using System.Collections.Immutable;
using System.Text;
using Restate.Sdk.Generators.Models;

namespace Restate.Sdk.Generators.Emitters;

internal static class ClientFactoryEmitter
{
    public static string Generate(ImmutableArray<ServiceInfo> services)
    {
        var sb = new StringBuilder(1024);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Restate.Sdk.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class RestateClientFactory");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        global::Restate.Sdk.ClientFactory.Register(static (context, type, key, options) =>");
        sb.AppendLine("        {");

        foreach (var service in services)
        {
            var ns = string.IsNullOrEmpty(service.Namespace) ? "" : $"global::{service.Namespace}.";
            var isKeyed = service.Kind == ServiceKind.VirtualObject || service.Kind == ServiceKind.Workflow;

            // Call client — I{Service}Client
            sb.AppendLine($"            if (type == typeof({ns}I{service.ClassName}Client))");
            if (isKeyed)
                sb.AppendLine($"                return new {ns}{service.ClassName}Client(context, key!);");
            else
                sb.AppendLine($"                return new {ns}{service.ClassName}Client(context);");

            // Send client — I{Service}SendClient
            sb.AppendLine($"            if (type == typeof({ns}I{service.ClassName}SendClient))");
            if (isKeyed)
                sb.AppendLine($"                return new {ns}{service.ClassName}SendClient(context, key!, options);");
            else
                sb.AppendLine($"                return new {ns}{service.ClassName}SendClient(context, options);");
        }

        sb.AppendLine("            return null;");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}