using System.Text;
using Restate.Sdk.Generators.Models;

namespace Restate.Sdk.Generators.Emitters;

internal static class ClientEmitter
{
    public static string Generate(ServiceInfo service)
    {
        var sb = new StringBuilder(2048);
        var isKeyed = service.Kind == ServiceKind.VirtualObject || service.Kind == ServiceKind.Workflow;

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine($"namespace {service.Namespace};");
            sb.AppendLine();
        }

        // Call interface — I{Service}Client
        sb.AppendLine($"public interface I{service.ClassName}Client");
        sb.AppendLine("{");
        foreach (var handler in service.Handlers)
        {
            var returnType = handler.OutputTypeFullName is not null
                ? $"global::System.Threading.Tasks.ValueTask<{handler.OutputTypeFullName}>"
                : "global::System.Threading.Tasks.ValueTask";
            var inputParam = handler.InputTypeFullName is not null
                ? $"{handler.InputTypeFullName} request"
                : "";
            sb.AppendLine($"    {returnType} {handler.Name}Async({inputParam});");

            // Future method — non-blocking, for concurrent patterns
            if (handler.OutputTypeFullName is not null)
            {
                var futureReturnType = $"global::Restate.Sdk.IDurableFuture<{handler.OutputTypeFullName}>";
                sb.AppendLine($"    {futureReturnType} {handler.Name}Future({inputParam});");
            }
        }

        sb.AppendLine("}");
        sb.AppendLine();

        // Send interface — I{Service}SendClient
        sb.AppendLine($"public interface I{service.ClassName}SendClient");
        sb.AppendLine("{");
        foreach (var handler in service.Handlers)
        {
            var inputParam = handler.InputTypeFullName is not null
                ? $"{handler.InputTypeFullName} request"
                : "";
            sb.AppendLine(
                $"    global::System.Threading.Tasks.ValueTask<global::Restate.Sdk.InvocationHandle> {handler.Name}Send({inputParam});");
        }

        sb.AppendLine("}");
        sb.AppendLine();

        // Call implementation
        EmitCallClient(sb, service, isKeyed);
        sb.AppendLine();

        // Send implementation
        EmitSendClient(sb, service, isKeyed);

        return sb.ToString();
    }

    private static void EmitCallClient(StringBuilder sb, ServiceInfo service, bool isKeyed)
    {
        sb.AppendLine($"internal sealed class {service.ClassName}Client : I{service.ClassName}Client");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::Restate.Sdk.Context _context;");
        if (isKeyed)
            sb.AppendLine("    private readonly string _key;");
        sb.AppendLine();

        if (isKeyed)
        {
            sb.AppendLine(
                $"    public {service.ClassName}Client(global::Restate.Sdk.Context context, string key)");
            sb.AppendLine("    {");
            sb.AppendLine("        _context = context;");
            sb.AppendLine("        _key = key;");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine($"    public {service.ClassName}Client(global::Restate.Sdk.Context context)");
            sb.AppendLine("    {");
            sb.AppendLine("        _context = context;");
            sb.AppendLine("    }");
        }

        foreach (var handler in service.Handlers)
        {
            sb.AppendLine();
            var requestArg = handler.InputTypeFullName is not null ? "request" : "(object?)null";
            var inputParam = handler.InputTypeFullName is not null
                ? $"{handler.InputTypeFullName} request"
                : "";

            if (handler.OutputTypeFullName is not null)
            {
                var returnType = $"global::System.Threading.Tasks.ValueTask<{handler.OutputTypeFullName}>";
                sb.AppendLine($"    public {returnType} {handler.Name}Async({inputParam})");

                if (isKeyed)
                    sb.AppendLine(
                        $"        => _context.Call<{handler.OutputTypeFullName}>(\"{service.ServiceName}\", _key, \"{handler.Name}\", {requestArg});");
                else
                    sb.AppendLine(
                        $"        => _context.Call<{handler.OutputTypeFullName}>(\"{service.ServiceName}\", \"{handler.Name}\", {requestArg});");

                // Future method
                sb.AppendLine();
                var futureReturnType = $"global::Restate.Sdk.IDurableFuture<{handler.OutputTypeFullName}>";
                sb.AppendLine($"    public {futureReturnType} {handler.Name}Future({inputParam})");

                if (isKeyed)
                    sb.AppendLine(
                        $"        => _context.CallFuture<{handler.OutputTypeFullName}>(\"{service.ServiceName}\", _key, \"{handler.Name}\", {requestArg});");
                else
                    sb.AppendLine(
                        $"        => _context.CallFuture<{handler.OutputTypeFullName}>(\"{service.ServiceName}\", \"{handler.Name}\", {requestArg});");
            }
            else
            {
                sb.AppendLine($"    public global::System.Threading.Tasks.ValueTask {handler.Name}Async({inputParam})");
                sb.AppendLine("    {");

                if (isKeyed)
                    sb.AppendLine(
                        $"        var task = _context.Call<object?>(\"{service.ServiceName}\", _key, \"{handler.Name}\", (object?)null);");
                else
                    sb.AppendLine(
                        $"        var task = _context.Call<object?>(\"{service.ServiceName}\", \"{handler.Name}\", (object?)null);");

                sb.AppendLine(
                    "        return task.IsCompletedSuccessfully ? default : new global::System.Threading.Tasks.ValueTask(task.AsTask());");
                sb.AppendLine("    }");
            }
        }

        sb.AppendLine("}");
    }

    private static void EmitSendClient(StringBuilder sb, ServiceInfo service, bool isKeyed)
    {
        sb.AppendLine($"internal sealed class {service.ClassName}SendClient : I{service.ClassName}SendClient");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::Restate.Sdk.Context _context;");
        if (isKeyed)
            sb.AppendLine("    private readonly string _key;");
        sb.AppendLine("    private readonly global::Restate.Sdk.SendOptions? _options;");
        sb.AppendLine();

        if (isKeyed)
        {
            sb.AppendLine(
                $"    public {service.ClassName}SendClient(global::Restate.Sdk.Context context, string key, global::Restate.Sdk.SendOptions? options)");
            sb.AppendLine("    {");
            sb.AppendLine("        _context = context;");
            sb.AppendLine("        _key = key;");
            sb.AppendLine("        _options = options;");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine(
                $"    public {service.ClassName}SendClient(global::Restate.Sdk.Context context, global::Restate.Sdk.SendOptions? options)");
            sb.AppendLine("    {");
            sb.AppendLine("        _context = context;");
            sb.AppendLine("        _options = options;");
            sb.AppendLine("    }");
        }

        foreach (var handler in service.Handlers)
        {
            sb.AppendLine();
            var requestArg = handler.InputTypeFullName is not null ? "request" : "(object?)null";
            var inputParam = handler.InputTypeFullName is not null
                ? $"{handler.InputTypeFullName} request"
                : "";

            sb.AppendLine(
                $"    public global::System.Threading.Tasks.ValueTask<global::Restate.Sdk.InvocationHandle> {handler.Name}Send({inputParam})");

            if (isKeyed)
                sb.AppendLine(
                    $"        => _context.Send(\"{service.ServiceName}\", _key, \"{handler.Name}\", {requestArg}, _options?.Delay, _options?.IdempotencyKey);");
            else
                sb.AppendLine(
                    $"        => _context.Send(\"{service.ServiceName}\", \"{handler.Name}\", {requestArg}, _options?.Delay, _options?.IdempotencyKey);");
        }

        sb.AppendLine("}");
    }
}