using System.Text;
using Restate.Sdk.Generators.Models;

namespace Restate.Sdk.Generators.Emitters;

internal static class InvokerEmitter
{
    public static string Generate(ServiceInfo service)
    {
        var sb = new StringBuilder(1024);
        var fqClass = string.IsNullOrEmpty(service.Namespace)
            ? $"global::{service.ClassName}"
            : $"global::{service.Namespace}.{service.ClassName}";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Restate.Sdk.Generated;");
        sb.AppendLine();
        sb.AppendLine($"internal static class {service.ClassName}Invokers");
        sb.AppendLine("{");

        for (var i = 0; i < service.Handlers.Length; i++)
        {
            if (i > 0) sb.AppendLine();
            EmitInvoker(sb, service.Handlers[i], fqClass);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitInvoker(StringBuilder sb, HandlerInfo handler, string fqClass)
    {
        sb.AppendLine($"    public static async global::System.Threading.Tasks.Task<object?> {handler.MethodName}(");
        sb.AppendLine(
            "        object instance, global::Restate.Sdk.Context context, object? input, global::System.Threading.CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var typed = ({fqClass})instance;");

        // Build the argument list for the call
        var args = new List<string>();

        args.Add($"({handler.ContextParameterType})context");

        if (handler.InputTypeFullName is not null)
            args.Add($"({handler.InputTypeFullName})input!");

        if (handler.HasCancellationToken)
            args.Add("ct");

        var argStr = string.Join(", ", args);
        var call = $"typed.{handler.MethodName}({argStr})";

        // Determine how to handle the return type
        if (handler.OutputTypeFullName is not null)
        {
            // Returns Task<T> or ValueTask<T> — await and box
            sb.AppendLine($"        return await {call}.ConfigureAwait(false);");
        }
        else
        {
            // Returns Task, ValueTask, or void — await (if async) and return null
            var returnType = handler.ReturnTypeFullName;
            if (returnType == "void" || returnType == "global::System.Void")
            {
                sb.AppendLine($"        {call};");
                sb.AppendLine("        return null;");
            }
            else
            {
                sb.AppendLine($"        await {call}.ConfigureAwait(false);");
                sb.AppendLine("        return null;");
            }
        }

        sb.AppendLine("    }");
    }
}