using System.Collections.Immutable;
using System.Text;
using Restate.Sdk.Generators.Models;

namespace Restate.Sdk.Generators.Emitters;

internal static class RegistrationEmitter
{
    public static string Generate(ImmutableArray<ServiceInfo> services)
    {
        var sb = new StringBuilder(1024);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("namespace Restate.Sdk.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("///     Source-generated AOT-friendly service registration.");
        sb.AppendLine("///     Eliminates reflection-based DI registration for NativeAOT compatibility.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class RestateRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///     Registers all discovered Restate services into the DI container without reflection.");
        sb.AppendLine("    ///     Call this from <c>RestateHostBuilder.BuildAot()</c> or directly in your DI setup.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddRestateGenerated(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        // Build the definitions array
        sb.AppendLine("        var definitions = new global::Restate.Sdk.Endpoint.ServiceDefinition[]");
        sb.AppendLine("        {");

        foreach (var service in services)
        {
            var fqClass = string.IsNullOrEmpty(service.Namespace)
                ? $"global::{service.ClassName}"
                : $"global::{service.Namespace}.{service.ClassName}";

            sb.AppendLine($"            global::Restate.Sdk.Endpoint.ServiceDefinitionRegistry.Get<{fqClass}>(),");
        }

        sb.AppendLine("        };");
        sb.AppendLine();

        // Build the types array
        sb.AppendLine("        var serviceTypes = new global::System.Type[]");
        sb.AppendLine("        {");

        foreach (var service in services)
        {
            var fqClass = string.IsNullOrEmpty(service.Namespace)
                ? $"global::{service.ClassName}"
                : $"global::{service.Namespace}.{service.ClassName}";

            sb.AppendLine($"            typeof({fqClass}),");
        }

        sb.AppendLine("        };");
        sb.AppendLine();

        // Call the public AddRestateAot method
        sb.AppendLine("        return global::Restate.Sdk.Hosting.RestateServiceCollectionExtensions.AddRestateAot(services, definitions, serviceTypes);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
