using System.Collections.Immutable;
using System.Text;
using Restate.Sdk.Generators.Models;

namespace Restate.Sdk.Generators.Emitters;

internal static class SerializationContextEmitter
{
    public static string Generate(ImmutableArray<ServiceInfo> services)
    {
        var types = new SortedSet<string>();

        foreach (var service in services)
            foreach (var handler in service.Handlers)
            {
                if (handler.InputTypeFullName is not null)
                    types.Add(handler.InputTypeFullName);
                if (handler.OutputTypeFullName is not null)
                    types.Add(handler.OutputTypeFullName);
            }

        var sb = new StringBuilder(1024);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("namespace Restate.Sdk.Generated;");
        sb.AppendLine();

        // Module initializer configures JsonSerde with sensible defaults.
        // For AOT, users should define their own [JsonSerializerContext] with
        // [JsonSerializable] attributes and pass it via JsonSerde.Configure().
        // Roslyn source generators cannot chain — the STJ generator won't see
        // types emitted by our generator, so we can't auto-generate the context.
        sb.AppendLine("internal static class RestateSerializationConfig");
        sb.AppendLine("{");

        // Emit discovered types as comments for documentation
        if (types.Count > 0)
        {
            sb.AppendLine("    // Handler types discovered at compile time.");
            sb.AppendLine("    // For AOT support, add these to your own JsonSerializerContext:");
            foreach (var type in types) sb.AppendLine($"    //   [JsonSerializable(typeof({type}))]");
            sb.AppendLine();
        }

        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void ConfigureJsonSerde()");
        sb.AppendLine("    {");
        sb.AppendLine("        var options = new JsonSerializerOptions");
        sb.AppendLine("        {");
        sb.AppendLine("            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,");
        sb.AppendLine("            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,");
        sb.AppendLine("        };");
        sb.AppendLine("        global::Restate.Sdk.JsonSerde.Configure(options);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}