using System.Collections.Immutable;
using System.Text;
using Restate.Sdk.Generators.Models;

namespace Restate.Sdk.Generators.Emitters;

internal static class ServiceDefinitionEmitter
{
    public static string Generate(ImmutableArray<ServiceInfo> services)
    {
        var sb = new StringBuilder(1024);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Restate.Sdk.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class ServiceDefinitions");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");

        foreach (var service in services)
        {
            var fqClass = string.IsNullOrEmpty(service.Namespace)
                ? $"global::{service.ClassName}"
                : $"global::{service.Namespace}.{service.ClassName}";

            var serviceType = service.Kind switch
            {
                ServiceKind.Service => "global::Restate.Sdk.Endpoint.ServiceType.Service",
                ServiceKind.VirtualObject => "global::Restate.Sdk.Endpoint.ServiceType.VirtualObject",
                ServiceKind.Workflow => "global::Restate.Sdk.Endpoint.ServiceType.Workflow",
                _ => "global::Restate.Sdk.Endpoint.ServiceType.Service"
            };

            sb.AppendLine($"        global::Restate.Sdk.Endpoint.ServiceDefinitionRegistry.Register<{fqClass}>(");
            sb.AppendLine("            new global::Restate.Sdk.Endpoint.ServiceDefinition");
            sb.AppendLine("            {");
            sb.AppendLine($"                Name = \"{service.ServiceName}\",");
            sb.AppendLine($"                Type = {serviceType},");
            sb.AppendLine(
                $"                Factory = static (sp) => sp.GetService(typeof({fqClass})) ?? throw new global::System.InvalidOperationException(\"Service '{fqClass}' not registered in DI\"),");
            sb.AppendLine("                Handlers = new global::Restate.Sdk.Endpoint.HandlerDefinition[]");
            sb.AppendLine("                {");

            foreach (var handler in service.Handlers)
            {
                var hasInput = handler.InputTypeFullName is not null ? "true" : "false";
                var hasOutput = handler.OutputTypeFullName is not null ? "true" : "false";
                var deserializerExpr = handler.InputTypeFullName is not null
                    ? $"static (data) => {{ var r = new global::System.Text.Json.Utf8JsonReader(data); return global::System.Text.Json.JsonSerializer.Deserialize(ref r, global::Restate.Sdk.JsonSerde.SerializerOptions.GetTypeInfo(typeof({handler.InputTypeFullName}))) ?? throw new global::System.InvalidOperationException(\"Deserialization returned null\"); }}"
                    : "null";

                sb.AppendLine("                    new global::Restate.Sdk.Endpoint.HandlerDefinition");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        Name = \"{handler.Name}\",");
                sb.AppendLine($"                        IsShared = {(handler.IsShared ? "true" : "false")},");
                sb.AppendLine($"                        Invoker = {service.ClassName}Invokers.{handler.MethodName},");
                sb.AppendLine($"                        HasInput = {hasInput},");
                sb.AppendLine($"                        HasOutput = {hasOutput},");
                sb.AppendLine($"                        InputDeserializer = {deserializerExpr},");
                if (handler.InactivityTimeout is not null)
                    sb.AppendLine($"                        InactivityTimeoutMs = (long)global::System.TimeSpan.Parse(\"{handler.InactivityTimeout}\").TotalMilliseconds,");
                if (handler.AbortTimeout is not null)
                    sb.AppendLine($"                        AbortTimeoutMs = (long)global::System.TimeSpan.Parse(\"{handler.AbortTimeout}\").TotalMilliseconds,");
                if (handler.IdempotencyRetention is not null)
                    sb.AppendLine($"                        IdempotencyRetentionMs = (long)global::System.TimeSpan.Parse(\"{handler.IdempotencyRetention}\").TotalMilliseconds,");
                if (handler.JournalRetention is not null)
                    sb.AppendLine($"                        JournalRetentionMs = (long)global::System.TimeSpan.Parse(\"{handler.JournalRetention}\").TotalMilliseconds,");
                if (handler.IngressPrivate)
                    sb.AppendLine("                        IngressPrivate = true,");
                sb.AppendLine("                    },");
            }

            sb.AppendLine("                },");
            if (service.WorkflowRetention is not null)
                sb.AppendLine($"                WorkflowRetentionMs = (long)global::System.TimeSpan.Parse(\"{service.WorkflowRetention}\").TotalMilliseconds,");
            sb.AppendLine("            });");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
