using System.Buffers;
using System.ComponentModel;

namespace Restate.Sdk.Endpoint;

/// <summary>
///     Describes a handler on a Restate service.
/// </summary>
[EditorBrowsable(EditorBrowsableState.Never)]
public sealed class HandlerDefinition
{
    /// <summary>Gets the handler name as exposed to the Restate runtime.</summary>
    public required string Name { get; init; }

    /// <summary>Gets a value indicating whether this handler uses shared access (read-only for virtual objects).</summary>
    public required bool IsShared { get; init; }

    /// <summary>Gets the delegate that invokes the handler method on a service instance.</summary>
    public required HandlerInvoker Invoker { get; init; }

    /// <summary>Gets a value indicating whether the handler accepts an input payload.</summary>
    public bool HasInput { get; init; }

    /// <summary>Gets a value indicating whether the handler produces an output payload.</summary>
    public bool HasOutput { get; init; }

    /// <summary>Gets the MIME content type for serialization. Defaults to <c>"application/json"</c>.</summary>
    public string ContentType { get; init; } = "application/json";

    /// <summary>
    ///     Compile-time typed deserializer for handler input. Generated by the source generator
    ///     to avoid the reflection-based <c>JsonSerializer.Deserialize(data, Type)</c> path.
    /// </summary>
    public Func<ReadOnlySequence<byte>, object?>? InputDeserializer { get; init; }

    /// <summary>
    ///     Optional documentation for this handler, shown in the Restate Admin API.
    ///     Markdown is the conventional format.
    /// </summary>
    public string? Documentation { get; init; }

    /// <summary>
    ///     Optional custom metadata for this handler, shown in the Restate Admin API.
    /// </summary>
    public IReadOnlyDictionary<string, string>? Metadata { get; init; }

    /// <summary>Maximum inactivity time before the runtime suspends this handler, in milliseconds.</summary>
    public long? InactivityTimeoutMs { get; init; }

    /// <summary>Maximum time to forcefully abort after inactivity timeout, in milliseconds.</summary>
    public long? AbortTimeoutMs { get; init; }

    /// <summary>Duration to retain idempotent responses, in milliseconds.</summary>
    public long? IdempotencyRetentionMs { get; init; }

    /// <summary>Duration to retain the invocation journal, in milliseconds.</summary>
    public long? JournalRetentionMs { get; init; }

    /// <summary>When true, this handler cannot be invoked via the Restate ingress HTTP API.</summary>
    public bool IngressPrivate { get; init; }
}
